version: "3.8"

services:

  web:
    image: nginx:1.21.0
    container_name: ${APP_NAME}_web
    hostname: ${APP_NAME}_web
    ports:
      - "80:80"
      - "443:443"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_PHP_SOCKET: ${APP_NAME}_php:9000
      LOG_STDOUT: /app/storage/logs/web.access.log
      LOG_STDERR: /app/storage/logs/web.errors.log
    volumes:
      - ./:/app
      - ./docker/nginx:/etc/nginx/conf.d
    working_dir: /app
    depends_on:
      - php

  node:
      image: node:14.21.3
      container_name: ${APP_NAME}_node
      hostname: ${APP_NAME}_node
      ports:
        - "5173:5173"
      platform: 'linux/arm64/v8'
      volumes:
          - ./:/app
      working_dir: /app
      command: tail -f /dev/null

  php:
    build:
      context: ./
      dockerfile: docker/conf/php/Dockerfile
    container_name: ${APP_NAME}_php
    hostname: ${APP_NAME}_php
    working_dir: /app
    volumes:
      - ./:/app/
      - ./storage/framework/tmp:/tmp
      - ./docker/conf/php/.bashrc:/root/.bashrc
      - ./docker/conf/php/.bash_aliases:/root/.bash_aliases
    environment:
      TERM: xterm-256color
      COMPOSER_ALLOW_SUPERUSER: 1
      XDEBUG_CONFIG: "client_host=${DOCKER_ADDRESS}"
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
    ports:
      - "6001:6001"
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - db
      - db_testing
    entrypoint: ["/bin/bash", "/app/docker/bin/php_start.sh"]

  db:
    image: postgis/postgis:14-3.3-alpine
    container_name: ${APP_NAME}_db
    hostname: ${APP_NAME}_db
    platform: 'linux/amd64'
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./storage/pgsql/:/var/lib/postgresql/data/

  db_testing:
    image: postgis/postgis:14-3.3-alpine
    platform: 'linux/amd64'
    container_name: ${APP_NAME}_db_testing
    hostname: ${APP_NAME}_db_testing
    ports:
      - 5433:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    tmpfs:
      - /var/lib/postgresql/data

  cache:
    image: nbtri/alpine-redis
    platform: 'linux/amd64'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ${APP_NAME}_cache
    hostname: ${APP_NAME}_cache
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  mailer:
    image: mailhog/mailhog
    platform: 'linux/amd64'
    container_name: ${APP_NAME}_mailer
    hostname: ${APP_NAME}_mailer
    ports:
      - "8025:8025"
      - "1025:1025"
